// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "@hey-api/client-fetch"
import type {
  RegisterUserData,
  RegisterUserError,
  RegisterUserResponse,
} from "./types.gen"

export const client = createClient(createConfig())

/**
 * Register an user
 */
export const registerUser = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    RegisterUserResponse,
    RegisterUserError
  >({
    ...options,
    url: "/api/v1/register",
  })
}
