// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  detail: string
}

export type UserCreate = {
  email: string
  username: string
  full_name: string
  password: string
}

export type UserRead = {
  email: string
  username: string
  full_name: string
  id: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type RegisterUserData = {
  body: UserCreate
}

export type RegisterUserResponse = UserRead

export type RegisterUserError = Message | HTTPValidationError

export type $OpenApiTs = {
  "/api/v1/register": {
    post: {
      req: RegisterUserData
      res: {
        /**
         * The Register user
         */
        "201": UserRead
        /**
         * Bad Request
         */
        "400": Message
        /**
         * Validation Error
         */
        "422": HTTPValidationError
      }
    }
  }
}
